package LocadoraVeiculo.GUI.cadastro;

import LocadoraVeiculo.dao.FabricanteDAO;
import LocadoraVeiculo.dao.ModeloDAO;
import LocadoraVeiculo.entity.Fabricante;
import LocadoraVeiculo.entity.Modelo;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class CadastroModeloEditarGUI extends javax.swing.JDialog {

    private Fabricante fabricante = new Fabricante();
    private FabricanteDAO daoF = new FabricanteDAO();
    private ModeloDAO daoM = new ModeloDAO();
    private Modelo modeloEditar = null;

    public CadastroModeloEditarGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        carregarComboBoxFabricante();
    }

    public void carregarModelo(int id) {
        modeloEditar = daoM.select(id);
        txtNomeModelo.setText(modeloEditar.getNome());

        List<Fabricante> fabricantes = daoF.select();
        DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();

        for (Fabricante fabricante : fabricantes) {
            comboBoxModel.addElement(fabricante.getNome());
        }
        cboFabricante.setModel(comboBoxModel);
        cboFabricante.setSelectedItem(modeloEditar.getFabricante().getNome());
    }

    public void carregarComboBoxFabricante() {

        List<Fabricante> listaFabricante = daoF.select();

        Object[] valoresModel = new Object[listaFabricante.size()];

        int i = 0;

        for (Fabricante fabricante1 : listaFabricante) {
            valoresModel[i] = fabricante1;

            i++;
        }

        DefaultComboBoxModel model = new DefaultComboBoxModel(valoresModel);

        cboFabricante.setModel(model);
    }

    public void limparCampos() {
        txtNomeModelo.setText("");
        cboFabricante.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeModelo = new javax.swing.JLabel();
        txtNomeModelo = new javax.swing.JTextField();
        lblFabricante = new javax.swing.JLabel();
        cboFabricante = new javax.swing.JComboBox();
        btnSalvar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNomeModelo.setText("Nome");

        lblFabricante.setText("Fabricante");

        cboFabricante.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cboFabricanteAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cboFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFabricanteActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNomeModelo)
                    .addComponent(txtNomeModelo)
                    .addComponent(lblFabricante)
                    .addComponent(cboFabricante, 0, 207, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFechar)
                .addGap(4, 4, 4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblNomeModelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFabricante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnFechar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Inserido outra forma de carregar o combobox do fabricante
    private void cboFabricanteAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cboFabricanteAncestorAdded

        /*
        List<Fabricante> lista = dao.select();
        
        cboFabricante.removeAll();
        
        for (Fabricante fabricantel : lista) {
            cboFabricante.addItem(fabricantel);
        }*/
    }//GEN-LAST:event_cboFabricanteAncestorAdded

    private void cboFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFabricanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboFabricanteActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (modeloEditar != null) {
            String nome = txtNomeModelo.getText();
            try {
                daoM.update(modeloEditar.getId(), nome);
                JOptionPane.showMessageDialog(this, "Modelo Alterado com Sucesso", "SUCESS", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        } else {
            String nome = txtNomeModelo.getText();
            Fabricante nomeFabricante = (Fabricante) cboFabricante.getSelectedItem();

            try {
                int idFabricante = nomeFabricante.getId();
                daoM.insert(nome, idFabricante);
                limparCampos();
                JOptionPane.showMessageDialog(this, "Modelo Inserido com Sucesso", "SUCESS", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cboFabricante;
    private javax.swing.JLabel lblFabricante;
    private javax.swing.JLabel lblNomeModelo;
    private javax.swing.JTextField txtNomeModelo;
    // End of variables declaration//GEN-END:variables
}
