package LocadoraVeiculo.GUI.cadastro;

import LocadoraVeiculo.dao.CarroDAO;
import LocadoraVeiculo.dao.FabricanteDAO;
import LocadoraVeiculo.dao.ModeloDAO;
import LocadoraVeiculo.entity.Carro;
import LocadoraVeiculo.entity.Fabricante;
import LocadoraVeiculo.entity.Modelo;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class CadastroCarroEditarGUI extends javax.swing.JDialog {

    private FabricanteDAO daoF = new FabricanteDAO();
    private ModeloDAO daoM = new ModeloDAO();
    private Carro carroEditar = null;
    private CarroDAO daoC = new CarroDAO();
    private List<Modelo> listaModelo = new ArrayList<>();
    private List<Fabricante> listaFabricante = new ArrayList<>();

    public CadastroCarroEditarGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        carregarComboBoxFabricante();
        carregarComboBoxModelo();
    }

    public void carregarCarro(int id) {
        carroEditar = daoC.select(id);
        txtPlaca.setText(carroEditar.getPlaca());
        txtCor.setText(carroEditar.getCor());
        txtAnoCarro.setText(String.valueOf(carroEditar.getAno()));
        txtValorCarro.setText(String.valueOf(carroEditar.getValorLocacao()));
        chkDisponivel.setSelected(carroEditar.getDisponivel());

        setComboFabricante(carroEditar.getFabricante());
        setComboModelo(carroEditar.getModelo());

    }

    public void setComboFabricante(Fabricante f) {
        for (Fabricante fabricanteProcura : listaFabricante) {
            if (fabricanteProcura.getId() == f.getId()) {
                cboNomeFabricante.setSelectedIndex(listaFabricante.indexOf(fabricanteProcura));
            }
        }
    }

    public void setComboModelo(Modelo m) {
        for (Modelo modeloProcura : listaModelo) {
            if (modeloProcura.getId() == m.getId()) {
                cboNomeModelo.setSelectedIndex(listaModelo.indexOf(modeloProcura));
            }
        }
    }

    public void carregarComboBoxFabricante() {
        listaFabricante = daoF.select();

        Object[] valoresModelFabricante = new Object[listaFabricante.size()];

        int i = 0;

        for (Fabricante fabricante1 : listaFabricante) {
            valoresModelFabricante[i] = fabricante1;

            i++;
        }

        DefaultComboBoxModel modelFabricante = new DefaultComboBoxModel(valoresModelFabricante);

        cboNomeFabricante.setModel(modelFabricante);
    }

    public void carregarComboBoxModelo() {
        listaModelo = daoM.select();

        Object[] valoresModelModelo = new Object[listaModelo.size()];

        int i = 0;

        for (Modelo modelo1 : listaModelo) {
            valoresModelModelo[i] = modelo1;

            i++;
        }

        DefaultComboBoxModel modelModelo = new DefaultComboBoxModel(valoresModelModelo);

        cboNomeModelo.setModel(modelModelo);
    }

    private void salvar() throws Exception {
//        Carro c = new Carro();
//        c.setFabricante(fabricante);
        int idFabricante = ((Fabricante) cboNomeFabricante.getSelectedItem()).getId();
        int idModelo = ((Modelo) cboNomeModelo.getSelectedItem()).getId();
        String placa = txtPlaca.getText();
        String cor = txtCor.getText();
        String disponivel = Boolean.toString(chkDisponivel.isSelected());
        int ano = Integer.parseInt(txtAnoCarro.getText());
        Double valorCarro = Double.parseDouble(txtValorCarro.getText());

//        if (carroEditar.getId() != 0) {
        if (carroEditar != null) {
            daoC.update(carroEditar.getId(), idFabricante, idModelo, placa, cor, disponivel, ano, valorCarro);
        } else {
            daoC.insert(idFabricante, idModelo, placa, cor, disponivel, ano, valorCarro);
        }

        String mensagem = carroEditar != null ? "Carro Alterado com Sucesso" : "Carro Inserido com Sucesso";
        JOptionPane.showMessageDialog(this, mensagem, "SUCESS", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFechar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        txtCor = new javax.swing.JTextField();
        lblCor = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        lblPlaca = new javax.swing.JLabel();
        cboNomeFabricante = new javax.swing.JComboBox<>();
        lblNomeFabricante = new javax.swing.JLabel();
        lblNomeModelo = new javax.swing.JLabel();
        lblDisponivel = new javax.swing.JLabel();
        lblAnoCarro = new javax.swing.JLabel();
        txtAnoCarro = new javax.swing.JTextField();
        txtValorCarro = new javax.swing.JTextField();
        lblValorCarro = new javax.swing.JLabel();
        chkDisponivel = new javax.swing.JCheckBox();
        cboNomeModelo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblCor.setText("Cor");

        lblPlaca.setText("Placa");

        cboNomeFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNomeFabricanteActionPerformed(evt);
            }
        });

        lblNomeFabricante.setText("Fabricante");

        lblNomeModelo.setText("Nome");

        lblDisponivel.setText("Dispon�vel");

        lblAnoCarro.setText("Ano Carro");

        lblValorCarro.setText("Valor Carro");

        chkDisponivel.setText("Sim");
        chkDisponivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDisponivelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNomeFabricante)
                    .addComponent(lblCor)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(lblPlaca)
                    .addComponent(cboNomeFabricante, 0, 166, Short.MAX_VALUE)
                    .addComponent(lblNomeModelo)
                    .addComponent(txtCor, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(cboNomeModelo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAnoCarro)
                    .addComponent(txtAnoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorCarro)
                    .addComponent(txtValorCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkDisponivel)
                    .addComponent(lblDisponivel))
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFechar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeModelo)
                    .addComponent(lblDisponivel))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkDisponivel)
                    .addComponent(cboNomeModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeFabricante)
                    .addComponent(lblAnoCarro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboNomeFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlaca)
                    .addComponent(lblValorCarro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblCor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnSalvar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboNomeFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNomeFabricanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboNomeFabricanteActionPerformed

    private void chkDisponivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDisponivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkDisponivelActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            salvar();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERRO", HEIGHT);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cboNomeFabricante;
    private javax.swing.JComboBox<String> cboNomeModelo;
    private javax.swing.JCheckBox chkDisponivel;
    private javax.swing.JLabel lblAnoCarro;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblDisponivel;
    private javax.swing.JLabel lblNomeFabricante;
    private javax.swing.JLabel lblNomeModelo;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblValorCarro;
    private javax.swing.JTextField txtAnoCarro;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtValorCarro;
    // End of variables declaration//GEN-END:variables
}
