package LocadoraVeiculo.GUI;

import LocadoraVeiculo.GUI.cadastro.CadastroFabricanteGUI;
import LocadoraVeiculo.GUI.cadastro.CadastroModeloGUI;

public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuItemFabricante = new javax.swing.JMenuItem();
        menuItemFabricante1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuCadastro.setText("Cadastro");

        menuItemFabricante.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuItemFabricante.setText("Fabricante");
        menuItemFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFabricanteActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemFabricante);

        menuItemFabricante1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuItemFabricante1.setText("Modelo");
        menuItemFabricante1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFabricante1ActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemFabricante1);

        jMenuBar1.add(menuCadastro);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFabricanteActionPerformed
        CadastroFabricanteGUI dialog = new CadastroFabricanteGUI(this,true);
        dialog.setVisible(true);
    }//GEN-LAST:event_menuItemFabricanteActionPerformed

    private void menuItemFabricante1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFabricante1ActionPerformed
        CadastroModeloGUI dialog = new CadastroModeloGUI(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_menuItemFabricante1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuItemFabricante;
    private javax.swing.JMenuItem menuItemFabricante1;
    // End of variables declaration//GEN-END:variables
}
